In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from scipy.stats import norm
import datetime as dt

In [39]:


# all inputs must be scalar

def blackscholes_price(K, T, S, vol, r=0, q=0, callput='call'):
    """Compute the call/put option price in the Black-Scholes model
    
    Parameters
    ----------
    K: scalar or array_like
        The strike of the option.
    T: scalar or array_like
        The maturity of the option, expressed in years (e.g. 0.25 for 3-month and 2 for 2 years)
    S: scalar or array_like
        The current price of the underlying asset.
    vol: scalar or array_like
        The implied Black-Scholes volatility.
    r: scalar or array_like
        The annualized risk-free interest rate, continuously compounded.
    q: scalar or array_like
        The annualized continuous dividend yield.
    callput: str
        Must be either 'call' or 'put'.

    Returns
    -------
    price: scalar or array_like
        The price of the option.

    Examples
    --------
    >>> blackscholes_price(95, 0.25, 100, 0.2, r=0.05, callput='put')
    1.5342604771222823
    """
    F = S*np.exp((r-q)*T)
    v = np.sqrt(vol**2*T)
    d1 = np.log(F/K)/v + 0.5*v
    d2 = d1 - v
    try:
        opttype = {'call':1, 'put':-1}[callput.lower()]
    except:
        raise ValueError('The value of callput must be either "call" or "put".')
    price = opttype*(F*norm.cdf(opttype*d1)-K*norm.cdf(opttype*d2))*np.exp(-r*T)
    return price

bs = np.vectorize(blackscholes_price)

def blackscholes_impv_scalar(K, T, S, value, r=0, q=0, callput='call', tol=1e-6, maxiter=500):
    """Compute implied vol in Black-Scholes model
    
    Parameters
    ----------
    K: scalar
        The strike of the option.
    T: scalar
        The maturity of the option.
    S: scalar
        The current price of the underlying asset.
    value: scalar
        The value of the option
    callput: str
        Must be either 'call' or 'put'

    Returns
    -------
    vol: scalar
        The implied vol of the option.
    """
    if (K <= 0) or (T <= 0) or (S <= 0):
        return np.nan
    F = S*np.exp((r-q)*T)
    K = K/F
    value = value*np.exp(r*T)/F
    try:
        opttype = {'call':1, 'put':-1}[callput.lower()]
    except:
        raise ValueError('The value of callput must be either "call" or "put".')
    # compute the time-value of the option
    value -= max(opttype * (1 - K), 0)
    if value < 0:
        return np.nan
    if (value == 0):
        return 0
    j = 1
    p = np.log(K)
    if K >= 1:
        x0 = np.sqrt(2 * p)
        x1 = x0 - (0.5 - K * norm.cdf(-x0) - value) * np.sqrt(2*np.pi)
        while (abs(x0 - x1) > tol*np.sqrt(T)) and (j < maxiter):
            x0 = x1
            d1 = -p/x1+0.5*x1
            x1 = x1 - (norm.cdf(d1) - K*norm.cdf(d1-x1)-value)*np.sqrt(2*np.pi)*np.exp(0.5*d1**2)
            j += 1
        return x1 / np.sqrt(T)
    else:
        x0 = np.sqrt(-2 * p)
        x1 = x0 - (0.5*K-norm.cdf(-x0)-value)*np.sqrt(2*np.pi)/K
        while (abs(x0-x1) > tol*np.sqrt(T)) and (j < maxiter):
            x0 = x1
            d1 = -p/x1+0.5*x1
            x1 = x1-(K*norm.cdf(x1-d1)-norm.cdf(-d1)-value)*np.sqrt(2*np.pi)*np.exp(0.5*d1**2)
            j += 1
        return x1 / np.sqrt(T)

# vectorized version
blackscholes_impv = np.vectorize(blackscholes_impv_scalar, excluded={'callput', 'tol', 'maxiter'})


def int_to_date(n):
    year = n//10000
    month = (n - year*10000)//100
    day = (n - year*10000-month*100)
    return dt.date(year,month,day)

def float_to_date(f):
    n = int(f)
    return int_to_date(n)

int_to_date = np.vectorize(int_to_date)
float_to_date = np.vectorize(float_to_date)

def time_delta_to_int(t):
    return t.days

time_delta_to_int = np.vectorize(time_delta_to_int)

In [34]:
T = np.array([1.,1.,1.])
K = np.array([90,100,110])
IV = np.array([0.22,0.20,0.18])

P = blackscholes_price(K, T, 100, IV, r=0, q=0, callput='call')
DKP = np.stack((T,K,P),axis=1)
DKP
dkp = pd.DataFrame(DKP)
dkp.to_csv("dkp.csv",index = False)
dkp
# blackscholes_impv(K, T, 100., P, r=0, q=0)
# help(pd.DataFrame.to_csv)

     0      1          2
0  1.0   90.0  14.252684
1  1.0  100.0   7.965567
2  1.0  110.0   3.557678

In [72]:
d = pd.read_csv("calls.csv")

initDate = int_to_date(d['date'][0])
D = (d['exdate']).values
D = time_delta_to_int(int_to_date(D)-initDate)/365

K = d['strike_price'].values
K = K/1000

P = d[['best_bid','best_offer']].values  # P = f(K,T)
P = (P[:,0]+P[:,1])/2

DKP = np.stack((D,K,P),axis=1)
# DKP = DKP[DKP[:,0] > 1.2 ]
# DKP = DKP[DKP[:,0] < 1.3 ]
dkp = pd.DataFrame(DKP)
dkp.to_csv("dkp.csv",index = False)
dkp

            0       1        2
0    0.046575  1275.0  128.000
1    0.046575  1300.0  103.600
2    0.046575  1325.0   79.800
3    0.046575  1350.0   57.350
4    0.046575  1365.0   44.400
5    0.046575  1370.0   40.550
6    0.046575  1375.0   36.650
7    0.046575  1380.0   32.650
8    0.046575  1385.0   29.200
9    0.046575  1390.0   25.800
10   0.046575  1395.0   22.350
11   0.046575  1400.0   19.550
12   0.046575  1405.0   16.800
13   0.046575  1410.0   14.000
14   0.046575  1415.0   11.550
15   0.046575  1420.0    9.350
16   0.046575  1425.0    7.550
17   0.046575  1430.0    5.950
18   0.046575  1435.0    4.650
19   0.046575  1440.0    3.575
20   0.046575  1445.0    2.700
21   0.046575  1450.0    2.000
22   0.046575  1455.0    1.475
23   0.046575  1460.0    1.075
24   0.046575  1465.0    0.725
25   0.046575  1470.0    0.525
26   0.046575  1475.0    0.450
27   0.046575  1480.0    0.350
28   0.046575  1485.0    0.275
29   0.046575  1490.0    0.250
..        ...     ...      ...
192  0.024658  1445.0    1.375
193  0.024658  1450.0    0.925
194  0.024658  1455.0    0.650
195  0.024658  1460.0    0.450
196  0.024658  1465.0    0.325
197  0.024658  1470.0    0.250
198  0.024658  1475.0    0.200
199  0.024658  1480.0    0.150
200  0.024658  1485.0    0.150
201  0.024658  1490.0    0.100
202  0.024658  1495.0    0.100
203  0.024658  1500.0    0.075
204  0.024658  1510.0    0.075
205  0.024658  1520.0    0.025
206  0.024658  1525.0    0.025
207  0.082192  1330.0   79.350
208  0.082192  1360.0   54.600
209  0.082192  1375.0   43.150
210  0.082192  1380.0   39.700
211  0.082192  1390.0   32.900
212  0.082192  1400.0   26.650
213  0.082192  1410.0   21.000
214  0.082192  1420.0   16.000
215  0.082192  1440.0    8.350
216  0.082192  1450.0    5.650
217  0.082192  1460.0    3.650
218  0.082192  1470.0    2.300
219  0.082192  1475.0    1.800
220  0.082192  1480.0    1.425
221  0.082192  1490.0    0.925

[222 rows x 3 columns]

In [90]:
preds = pd.read_csv("preds.csv",header = None)
Preds = preds.values
Preds = Preds[:,0]
comp = pd.DataFrame(np.stack((P,Preds),axis =1))
comp

           0          1
0    128.000  124.78800
1    103.600  100.83900
2     79.800   77.87580
3     57.350   56.12190
4     44.400   44.49870
5     40.550   40.79610
6     36.650   37.15890
7     32.650   33.60890
8     29.200   30.08190
9     25.800   26.72810
10    22.350   23.41990
11    19.550   20.36950
12    16.800   17.71340
13    14.000   15.36990
14    11.550   13.31390
15     9.350   11.56330
16     7.550   10.12080
17     5.950    8.98223
18     4.650    8.07322
19     3.575    7.34422
20     2.700    6.64422
21     2.000    5.98340
22     1.475    5.38340
23     1.075    4.78996
24     0.725    4.28996
25     0.525    3.91053
26     0.450    3.56053
27     0.350    3.21053
28     0.275    2.90503
29     0.250    2.65503
..       ...        ...
192    1.375    0.00000
193    0.925    0.00000
194    0.650    0.00000
195    0.450    0.00000
196    0.325    0.00000
197    0.250    0.00000
198    0.200    0.00000
199    0.150    0.00000
200    0.150    0.00000
201    0.100    0.00000
202    0.100    0.00000
203    0.075    0.00000
204    0.075    0.00000
205    0.025    0.00000
206    0.025    0.00000
207   79.350   91.20480
208   54.600   67.57940
209   43.150   56.32880
210   39.700   52.66030
211   32.900   45.50140
212   26.650   38.71760
213   21.000   32.26350
214   16.000   26.42980
215    8.350   17.53100
216    5.650   14.16820
217    3.650   11.24170
218    2.300    8.86830
219    1.800    7.87213
220    1.425    7.06920
221    0.925    5.85900

[222 rows x 2 columns]

In [93]:
preds = pd.read_csv("preds.csv",header = None)
Preds = preds.values
Preds = Preds[:,0]
comp = pd.DataFrame(np.stack((D,K,P,Preds),axis =1))
comp

            0       1        2           3
0    0.046575  1275.0  128.000  127.924000
1    0.046575  1300.0  103.600  103.840000
2    0.046575  1325.0   79.800   80.535400
3    0.046575  1350.0   57.350   58.382400
4    0.046575  1365.0   44.400   45.790700
5    0.046575  1370.0   40.550   41.725900
6    0.046575  1375.0   36.650   37.730800
7    0.046575  1380.0   32.650   33.810200
8    0.046575  1385.0   29.200   29.976300
9    0.046575  1390.0   25.800   26.256100
10   0.046575  1395.0   22.350   22.700100
11   0.046575  1400.0   19.550   19.389000
12   0.046575  1405.0   16.800   16.417000
13   0.046575  1410.0   14.000   13.865100
14   0.046575  1415.0   11.550   11.764200
15   0.046575  1420.0    9.350   10.087500
16   0.046575  1425.0    7.550    8.758240
17   0.046575  1430.0    5.950    7.688220
18   0.046575  1435.0    4.650    6.798630
19   0.046575  1440.0    3.575    6.031770
20   0.046575  1445.0    2.700    5.353240
21   0.046575  1450.0    2.000    4.743890
22   0.046575  1455.0    1.475    4.193460
23   0.046575  1460.0    1.075    3.696370
24   0.046575  1465.0    0.725    3.247640
25   0.046575  1470.0    0.525    2.843350
26   0.046575  1475.0    0.450    2.480790
27   0.046575  1480.0    0.350    2.156580
28   0.046575  1485.0    0.275    1.868160
29   0.046575  1490.0    0.250    1.612640
..        ...     ...      ...         ...
192  0.024658  1445.0    1.375    0.000081
193  0.024658  1450.0    0.925    0.000010
194  0.024658  1455.0    0.650    0.000003
195  0.024658  1460.0    0.450    0.000000
196  0.024658  1465.0    0.325    0.000000
197  0.024658  1470.0    0.250    0.000000
198  0.024658  1475.0    0.200    0.000000
199  0.024658  1480.0    0.150    0.000000
200  0.024658  1485.0    0.150    0.000000
201  0.024658  1490.0    0.100    0.000000
202  0.024658  1495.0    0.100    0.000000
203  0.024658  1500.0    0.075    0.000000
204  0.024658  1510.0    0.075    0.000000
205  0.024658  1520.0    0.025    0.000000
206  0.024658  1525.0    0.025    0.000000
207  0.082192  1330.0   79.350   84.348500
208  0.082192  1360.0   54.600   60.545600
209  0.082192  1375.0   43.150   49.245100
210  0.082192  1380.0   39.700   45.576600
211  0.082192  1390.0   32.900   38.411200
212  0.082192  1400.0   26.650   31.561100
213  0.082192  1410.0   21.000   25.257200
214  0.082192  1420.0   16.000   19.826400
215  0.082192  1440.0    8.350   12.042400
216  0.082192  1450.0    5.650    9.386180
217  0.082192  1460.0    3.650    7.280460
218  0.082192  1470.0    2.300    5.596170
219  0.082192  1475.0    1.800    4.885380
220  0.082192  1480.0    1.425    4.251550
221  0.082192  1490.0    0.925    3.188120

[222 rows x 4 columns]